spring.application.name=Internship-Backend

server.port=1305

spring.datasource.url=jdbc:mysql://localhost:3306/intern
spring.datasource.username=root
spring.datasource.password=Satish@4_7_7

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

 spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vemulasatishteja537@gmail.com
spring.mail.password=pkmmpcugfdkdpyzs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
